### PR TITLE
Add function for deciphering MS TGTs

### PR DESCRIPTION
**Pull request by dmulder**
Implements # .

- [x] cargo fmt has been run
- [ ] cargo test has been run and passes
- [ ] documentation has been updated with relevant examples (if relevant)

### CODE REVIEW

**Comment by dmulder** [comment]
See https://github.com/kanidm/hsm-crypto/pull/36

**Comment by dmulder** [comment]
The tests are failing because it depends on changes in hsm-crypto. Those will need to merge first.

**Comment by dmulder** [comment]
Sigh, and now I realize my final code didn't even utilize these changes. That's why I never pushed them! Sorry for the confusion.

**Comment by Firstyear** [comment]
No problem <3

**Pull request closed without merging**
